# =====================================================================
# B9 = B8 + REAL multi-sweep spanning ~1.5s (past keyframes + sweeps).
#
# Why this row exists
# -------------------
# Stage 2 planning surfaced that the modern mmdet3d info pkls used by
# B0..B8 carry no ``lidar_sweeps`` field — so ``LoadPointsFromMultiSweeps``
# falls into ``pad_empty_sweeps`` and silently duplicates the keyframe
# 10× with time=0. Every "multi-sweep" run so far was effectively
# single-keyframe.
#
# B9 fixes this by using ``nuscenes_infos_{train_25pct,val}_mkf30.pkl``
# (generated by ``projects/bevdet/build_multikeyframe_infos.py``), which
# walks the LIDAR_TOP ``sample_data.prev`` chain via the nuScenes
# dev-kit to populate ``lidar_sweeps`` with up to 30 real records
# covering ~1.5 s — about 3× the original "10-sweep" intent and the
# Stage 2 temporal window. Each sweep has the proper ``lidar2sensor``
# ego-warp matrix.
#
# Detector: same MultiTokenTemporalBEVFusion as B8 V2, but with
# ``window_seconds=1.5`` (matching the new sweep span). Detector code
# is unchanged — only the data + config differ.
# =====================================================================

_base_ = ['./B8_multitoken_temporal.py']

point_cloud_range = [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]
backend_args = None

# --- Full pipelines override (only sweeps_num changes vs B8) ---
train_pipeline = [
    dict(type='BEVLoadMultiViewImageFromFiles', to_float32=True,
         color_type='color', backend_args=backend_args),
    dict(type='LoadPointsFromFile', coord_type='LIDAR',
         load_dim=5, use_dim=5, backend_args=backend_args),
    dict(type='LoadPointsFromMultiSweeps',
         sweeps_num=30,             # ← was 9 in the inherited base
         load_dim=5, use_dim=5,
         pad_empty_sweeps=True, remove_close=True,
         backend_args=backend_args),
    dict(type='LoadAnnotations3D', with_bbox_3d=True,
         with_label_3d=True, with_attr_label=False),
    dict(type='ImageAug3D', final_dim=[256, 704],
         resize_lim=[0.38, 0.55], bot_pct_lim=[0.0, 0.0],
         rot_lim=[-5.4, 5.4], rand_flip=True, is_train=True),
    dict(type='BEVFusionGlobalRotScaleTrans',
         scale_ratio_range=[0.9, 1.1],
         rot_range=[-0.78539816, 0.78539816], translation_std=0.5),
    dict(type='BEVFusionRandomFlip3D'),
    dict(type='PointsRangeFilter', point_cloud_range=point_cloud_range),
    dict(type='ObjectRangeFilter', point_cloud_range=point_cloud_range),
    dict(type='ObjectNameFilter',
         classes=['car', 'truck', 'construction_vehicle', 'bus', 'trailer',
                  'barrier', 'motorcycle', 'bicycle', 'pedestrian',
                  'traffic_cone']),
    dict(type='GridMask', use_h=True, use_w=True, max_epoch=6, rotate=1,
         offset=False, ratio=0.5, mode=1, prob=0.0, fixed_prob=True),
    dict(type='PointShuffle'),
    dict(type='Pack3DDetInputs',
         keys=['points', 'img', 'gt_bboxes_3d', 'gt_labels_3d',
               'gt_bboxes', 'gt_labels'],
         meta_keys=['cam2img', 'ori_cam2img', 'lidar2cam', 'lidar2img',
                    'cam2lidar', 'ori_lidar2img', 'img_aug_matrix',
                    'box_type_3d', 'sample_idx', 'lidar_path', 'img_path',
                    'transformation_3d_flow', 'pcd_rotation',
                    'pcd_scale_factor', 'pcd_trans', 'img_aug_matrix',
                    'lidar_aug_matrix', 'num_pts_feats']),
]

test_pipeline = [
    dict(type='BEVLoadMultiViewImageFromFiles', to_float32=True,
         color_type='color', backend_args=backend_args),
    dict(type='LoadPointsFromFile', coord_type='LIDAR',
         load_dim=5, use_dim=5, backend_args=backend_args),
    dict(type='LoadPointsFromMultiSweeps',
         sweeps_num=30,             # ← was 9 in the inherited base
         load_dim=5, use_dim=5,
         pad_empty_sweeps=True, remove_close=True,
         backend_args=backend_args),
    dict(type='PointsRangeFilter', point_cloud_range=point_cloud_range),
    dict(type='ImageAug3D', final_dim=[256, 704],
         resize_lim=[0.48, 0.48], bot_pct_lim=[0.0, 0.0],
         rot_lim=[0.0, 0.0], rand_flip=False, is_train=False),
    dict(type='Pack3DDetInputs',
         keys=['img', 'points', 'gt_bboxes_3d', 'gt_labels_3d'],
         meta_keys=['cam2img', 'ori_cam2img', 'lidar2cam', 'lidar2img',
                    'cam2lidar', 'img_aug_matrix', 'box_type_3d',
                    'sample_idx', 'lidar_path', 'img_path',
                    'num_pts_feats']),
]

# --- Wire pipelines + new ann files into the dataloaders ---
train_dataloader = dict(
    dataset=dict(
        # CBGSDataset wraps NuScenesDataset; replace ann_file + pipeline
        # in the inner dataset.
        dataset=dict(
            ann_file='nuscenes_infos_train_25pct_mkf30.pkl',
            pipeline=train_pipeline,
        ),
    ),
)
val_dataloader = dict(
    dataset=dict(
        ann_file='nuscenes_infos_val_mkf30.pkl',
        pipeline=test_pipeline,
    ),
)
test_dataloader = val_dataloader

# Same registered evaluator as the rest of the ablation chain; just
# point it at the new val ann_file so the NuScenesMetric writes the
# right comparison.
val_evaluator = dict(ann_file='data/nuscenes/nuscenes_infos_val_mkf30.pkl')
test_evaluator = val_evaluator

# --- Temporal model: same class, window matches the new sweep span ---
model = dict(
    type='MultiTokenTemporalBEVFusion',
    num_buckets=4,
    window_seconds=1.5,            # was 0.5 in B8
    num_attn_heads=4,
    attn_dropout=0.0,
)
