# =====================================================================
# B18 — V9 mix + Waymo pseudo-labels from unlabeled train scenes.
#
# Same recipe as B14 (Waymo v1 GT + nuScenes 25%) but with a third
# ConcatDataset member: pseudo-labels generated by our
# bulk_pseudo_label_v1.py pipeline on 4 Waymo training tfrecords that
# V9 had never seen (segments 10517728..., 10518979..., 10526338...,
# 10584247...).
#
# The pseudo-labeled frames live alongside the GT v1 extracts under
# {WAYMO_V1_ROOT}/{seg}/f_*.npz — extract_waymo_v1.py was run on the
# same 4 tfrecords so LoadWaymoFrameFromInfo can read them via the
# existing waymo_v1:// URI dispatch.
#
# Hypothesis: pseudo-labels add *new* training distribution (not
# replicas of V9 frames as the V13 curator did), which is what the
# Ped/Cyc plateau in V9/V12/V13 was bottlenecked on.
#
# Will be reported as V14 in the paper.
# =====================================================================

_base_ = ['./B14_waymo_nuscenes_mixed.py']

# Path to the pseudo-label info.pkl (built by build_pseudo_label_info.py).
PSEUDO_INFO_PATH = (
    '/fs/atipa/data/rnd-liu/MyRepo/DeepDataMiningLearning/'
    'data/waymo_finetune/waymo_v1_infos_train_pseudo.pkl')

# Pseudo-label dataset entry. Uses the SAME WaymoFineTuneDataset class +
# pipeline as the GT v1 stream, just a different ann_file. The custom
# LoadWaymoFrameFromInfo transform reads from waymo_v1:// URIs, which
# resolve into the per-frame npz layout regardless of GT-vs-pseudo
# provenance.
pseudo_dataset = dict(
    type='WaymoFineTuneDataset',
    data_root=_base_.data_root_waymo,
    ann_file=PSEUDO_INFO_PATH,
    pipeline=_base_.waymo_train_pipeline,
    modality=_base_.input_modality,
    test_mode=False,
    metainfo=_base_.common_metainfo,
    box_type_3d='LiDAR',
    waymo_root='', waymo_split='',
    y_flip_on_load=False,
    backend_args=None,
)

train_dataloader = dict(
    _delete_=True,
    batch_size=8, num_workers=4, persistent_workers=True, pin_memory=True,
    prefetch_factor=2,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='ConcatDataset',
        datasets=[_base_.waymo_dataset,   # V9's Waymo GT (4,453 frames)
                  _base_.nus_dataset,     # V9's nuScenes 25% mkf30
                  pseudo_dataset],        # NEW pseudo-labeled scenes
        ignore_keys=['version', 'dataset', 'categories', 'info_version',
                     'sample_idx_to_data_idx', 'source_jsonl'],
    ),
)

# Same 1-epoch / cosine schedule as B14. Total dataset ~size up by
# pseudo-label count; iter budget grows proportionally.
train_cfg = dict(by_epoch=True, max_epochs=1)
